baseURL = 'https://sarray.de/'
languageCode = 'en-us'
title = 'Sarray Solutions'
theme = 'schlicht'
publishDir = 'docs'
enableRobotsTXT = true

[params]
  description = "Salman Sarray is a Performance Engineering Consultant based in Munich, Germany."

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Articles'
    pageRef = '/blog'
    weight = 20

  [[menus.main]]
    name = 'About'
    pageRef = '/about/'
    weight = 30

  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact/'
    weight = 40

  [[menus.main]]
    name = 'GitHub'
    url = 'https://github.com/msal4'
    weight = 50
